spring:
  datasource:
    url: jdbc:p6spy:mysql://127.0.0.1:3306/testdemo?useSSL=false&useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: root
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    hikari:
      minimum-idle: 5
      maximum-pool-size: 15
      auto-commit: true
      idle-timeout: 30000
      pool-name: DatebookHikariCP
      max-lifetime: 1800000
      connection-timeout: 30000
      validation-timeout: 3000
      login-timeout: 5

  ## redis配置
  redis:
    # redis服务端口号
    port: 6379
    # redis服务地址
    host: 127.0.0.1
    # lettuce连接池配置
    lettuce:
      pool:
        # 连接池最大阻塞等待时间
        max-wait: 1000ms
        # 最大空闲数
        max-idle: 8
        # 最小空闲数
        min-idle: 1
        # 最大连接数
        max-active: 8
      # 关闭超时时间
      shutdown-timeout: 100ms
    timeout: 10000ms

redis:
  default:
    timeout: 300
  key:
    # 为项目设置一个缓存key的前缀
    prefix: bookDemo.server.

mybatis-plus:
  mapper-locations: classpath:/mapper/*Mapper.xml
  type-aliases-package: com.example.testdemo.entity.po
  configuration:
    # 取消驼峰下划线转换
    map-underscore-to-camel-case: false
  global-config:
    db-config:
      id-type: uuid
      # 第二种方法，在配置文件里设置update时的字段策略，这里选择ignored，即忽略检测null字段，即可进行全字段更新
#      update-strategy: ignored

http:
  # 设置连接超时时间，单位为毫秒
  connectTimeout: 10000
  # 设置读取超时时间，单位为秒
  readTimeout: 10
  # 设置写超时时间，单位为秒
  writeTimeout: 10
  # 最大空闲连接数
  maxIdleConnections: 20
  # 长连接超时时间，单位为分钟
  keepAliveDuration: 5

### 指定日志配置文件
log:
  url: testdemo_log/
server:
  port: 8080
